keys:
  - &munkie_workstation  age180veg2flytxe6s53j8etg9j9jfee5srch84jt2y8zd3x6cw0xe3qxplk5s
  - &pc_anders           age1tag1qww48hmf9ua8jnrte8x9t854mfp79rpuvezprykewyjgehgxaqru5r73nex
  - &munkien             age1mlua0dm2g5ppdgspr58jeegmeu2fl7752tfzz4c0maz22mqdqdsq9phnle

creation_rules:
  # Global Secrets: Admin + All Hosts
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
        - *munkien
        - *munkie_workstation
        - *pc_anders

  # Host-specific Secrets: Admin + Specific Host
  - path_regex: hosts/server-home-1/secrets\.yaml$
    key_groups:
      - age:
        - *munkien
        - *munkie_workstation

  - path_regex: hosts/pc-anders/secrets\.yaml$
    key_groups:
      - age:
        - *munkien
        - *pc_anders
