keys:
  - &pc_anders           age1euv3gnx5u0t8ee0c8me86jxee5rvz5vf4ez8n4xcfy758cw7xddqt62x8l
  - &pc_anders_tpm       age1tag1qww48hmf9ua8jnrte8x9t854mfp79rpuvezprykewyjgehgxaqru5r73nex
  - &munkien             age1mlua0dm2g5ppdgspr58jeegmeu2fl7752tfzz4c0maz22mqdqdsq9phnle

creation_rules:
  - path_regex: hosts/pc-anders/secrets\.yaml$
    key_groups:
      - age:
          - *pc_anders
          - *pc_anders_tpm
          - *munkien