# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [];
   boot.initrd.supportedFileSystems = ["btrfs"];
  boot.initrd.availableKernelModules = [
    "sd_mod"
    "sr_mod"
    "hv_vmbus" 
  "hv_storvsc"  # Denne er kritisk for at se disken
  "hv_utils" 
  "hv_netvsc" 
  "xhci_pci" 
  "sd_mod"
    "hyperv_keyboard"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

hardware.enableAllHardware = true;


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.hypervGuest.enable = true;
}
