# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["virtio_pci" "virtio_scsi" "virtio_blk" "virtio_net" "virtio_balloon" "virtio_ring"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  ##########
  # Impermanence
  #########
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = ["defaults" "size=4G" "mode=755"];
    neededForBoot = true;
  };
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/91de1bf8-e8ce-4c3b-a22a-9ba38dee9d66";
    fsType = "ext4";
  };
  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/91de1bf8-e8ce-4c3b-a22a-9ba38dee9d66";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/91de1bf8-e8ce-4c3b-a22a-9ba38dee9d66";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/a83a052e-1927-49ba-94dc-b86faef428ba";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
