name: "Check and Build NixOS Hosts"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  verify:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [pc-anders, server-home-1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Flake Check
        run: nix flake check

      - name: Dry-run build host configuration
        run: nix build --dry-run .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
